### ISSUE TITLE
Norwegian translation

### ISSUE THREAD

**Issue by JanConGitHub** [matdahl/todolist#9]
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the todolist.todolist.mdahl package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: todolist.todolist.mdahl\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-03-16 19:24+0100\n"
"PO-Revision-Date: 2021-03-16 19:29+0100\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: nb\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 2.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../qml/Main.qml:67 todolist.desktop.in.h:1
msgid "To Do Lists"
msgstr "Gjøremålsliste"

#: ../qml/components/SortModeSelect.qml:84
msgid "Sort tasks by"
msgstr "Sorter oppgaver etter"

#: ../qml/components/SortModeSelect.qml:98
#: ../qml/panels/TaskInsertBottomEdge.qml:108
msgid "Deadline"
msgstr "Frist"

#: ../qml/components/SortModeSelect.qml:98
msgid "Name"
msgstr "Navn"

#: ../qml/components/SortModeSelect.qml:98
#: ../qml/panels/TaskInsertBottomEdge.qml:97
msgid "Priority"
msgstr "Prioritet"

#: ../qml/components/ToDoListHeader.qml:67
msgid "deadline"
msgstr "frist"

#: ../qml/components/ToDoListHeader.qml:90
msgid "task"
msgstr "oppgave"

#: ../qml/components/ToDoListHeader.qml:113
msgid "priority"
msgstr "prioritet"

#: ../qml/components/ToDoListItem.qml:87
msgid "> 1 week"
msgstr "> 1 uke"

#: ../qml/components/ToDoListItem.qml:88
msgid "in %1 days"
msgstr "innen %1 dager"

#: ../qml/components/ToDoListItem.qml:89
msgid "tomorrow"
msgstr "i morgen"

#: ../qml/components/ToDoListItem.qml:90
msgid "today"
msgstr "i dag"

#: ../qml/components/ToDoListItem.qml:91
msgid "overdue"
msgstr "forfalt"

#: ../qml/components/ToDoListItem.qml:92 ../qml/dialogs/TaskEditDialog.qml:91
#: ../qml/panels/TaskInsertBottomEdge.qml:122
msgid "no deadline"
msgstr "ingen frist"

#: ../qml/dialogs/TaskEditDialog.qml:50 ../qml/panels/ListPanel.qml:78
#: ../qml/panels/ListPanel.qml:80 ../qml/panels/ListPanel.qml:88
#: ../qml/panels/ListPanel.qml:106 ../qml/panels/ListPanel.qml:108
#: ../qml/panels/TaskInsertBottomEdge.qml:15
#: ../qml/panels/TaskInsertBottomEdge.qml:83
msgid "other"
msgstr "andre"

#: ../qml/dialogs/TaskEditDialog.qml:101
msgid "abort"
msgstr "avbryt"

#: ../qml/dialogs/TaskEditDialog.qml:105
msgid "apply changes"
msgstr "bruk endringer"

#: ../qml/panels/ListPanel.qml:78
msgid "All"
msgstr "Alle"

#: ../qml/panels/ListPanel.qml:79 ../qml/panels/ListPanel.qml:88
#: ../qml/panels/ListPanel.qml:93 ../qml/panels/ListPanel.qml:95
msgid "all"
msgstr "alle"

#: ../qml/panels/SettingsCategoriesPanel.qml:9
msgid "Manage Categories"
msgstr "Administrer kategorier"

#: ../qml/panels/SettingsCategoriesPanel.qml:19
msgid "new category"
msgstr "ny kategori"

#: ../qml/panels/SettingsPanel.qml:8
msgid "Settings"
msgstr "Innstillinger"

#: ../qml/panels/SettingsPanel.qml:14
msgid "Categories"
msgstr "Kategorier"

#: ../qml/panels/SettingsPanel.qml:19
msgid "Parameters"
msgstr "Parametre"

#: ../qml/panels/SettingsPanel.qml:23
msgid "Highest Priority"
msgstr "Høyeste prioritet"

#: ../qml/panels/SettingsPanel.qml:37
msgid "Default Priority"
msgstr "Standard prioritet"

#: ../qml/panels/SettingsPanel.qml:45
msgid "Set deadline by default"
msgstr "Angi frist som standard"

#: ../qml/panels/SettingsPanel.qml:51
msgid "Default offset for deadline (days)"
msgstr "Standardforskyvning for frist (dager)"

#: ../qml/panels/SettingsPanel.qml:59
msgid "Appearance"
msgstr "Utseende"

#: ../qml/panels/SettingsPanel.qml:62
msgid "Use default theme"
msgstr "Bruk standardtema"

#: ../qml/panels/SettingsPanel.qml:69
msgid "Dark Mode"
msgstr "Mørkt modus"

#: ../qml/panels/SettingsPanel.qml:76
msgid "Color"
msgstr "Farge"

#: ../qml/panels/TaskInsertBottomEdge.qml:11
msgid "new task"
msgstr "ny oppgave"

#: ../qml/panels/TaskInsertBottomEdge.qml:66
msgid "New Task"
msgstr "Ny Oppgave"

#: ../qml/panels/TaskInsertBottomEdge.qml:79
msgid "Category"
msgstr "Kategori"

#: ../qml/panels/TaskInsertBottomEdge.qml:88
msgid "Task name"
msgstr "Oppgavenavn"

#: ../qml/panels/TaskInsertBottomEdge.qml:93
msgid "insert task name"
msgstr "fyll ut oppgavenavn"

#: ../qml/panels/TaskInsertBottomEdge.qml:135
msgid "Cancel"
msgstr "Avbryt"

#: ../qml/panels/TaskInsertBottomEdge.qml:140
msgid "Insert"
msgstr "Sett inn"

#~ msgid "To Do List"
#~ msgstr "Gjøremålsliste"

#~ msgid "in "
#~ msgstr "in "

**Comment by JanConGitHub** [comment]
Code translated with HTML codes for Norwegian special characters.
If special characters can be used instead of HTML code, it have to be replaced to:

Special characters in Norwegian:

Character : HTML code
æ 	: &aelig;
Æ 	: &AElig;
ø 	: &oslash;
Ø 	: &Oslash;
å 	: &aring;
Å 	: &Aring;

**Comment by matdahl** [comment]
Thanks for translating the app! I've seen that there was still an old version of the .pot file in the repository. I now updated it (the recent file is called `todolist.matdahl.pot` instead of `todolist.todolist.mdahl.pot`).
Can you update your translation with the new .pot and make a PR?

**Comment by matdahl** [comment]
Thanks for the PR! The translations are now included in the OpenStore Version of the app.
